/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UsaLink {
        "href": string;
    }
}
declare global {
    interface HTMLUsaLinkElement extends Components.UsaLink, HTMLStencilElement {
    }
    var HTMLUsaLinkElement: {
        prototype: HTMLUsaLinkElement;
        new (): HTMLUsaLinkElement;
    };
    interface HTMLElementTagNameMap {
        "usa-link": HTMLUsaLinkElement;
    }
}
declare namespace LocalJSX {
    interface UsaLink {
        "href"?: string;
    }
    interface IntrinsicElements {
        "usa-link": UsaLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "usa-link": LocalJSX.UsaLink & JSXBase.HTMLAttributes<HTMLUsaLinkElement>;
        }
    }
}
