name: Code formatting
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run prettier JavaScript
        run: "npm run prettier:js"
      - name: Run prettier Markdown
        run: "npm run prettier:md"
