name: Generate New Playwright Screenshots
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to checkout and run tests on'
        required: true
        type: string

jobs:
  screenshots:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
    env:
      HOME: /root
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin v6.0.2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright to generate screenshots
        run: npx playwright test --config=./packages/elements/config/playwright.config.ts --update-snapshots

      - name: Upload new screenshots
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # pin v7.0.0
        with:
          name: playwright-snapshots
          path: packages/elements/e2e/**/*-snapshots/
          retention-days: 30
